// auth actions
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const REMOVE_ERROR = "REMOVE_ERROR";

//contacts actions
export const SET_FILTERED_CONTACTS = "SET_FILTERED_CONTACTS";
export const SET_SELECTED_ACTIVE = "SET_SELECTED_ACTIVE";
export const FILTER_CONTACTS = "FILTER_CONTACTS";

//active contact
export const SELECT_ACTIVE_CONTACT = "SELECT_ACTIVE_CONTACT";
export const DESELECT_ACTIVE_CONTACT = "DESELECT_ACTIVE_CONTACT";

//notifications
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const CONTACT_CREATED_SUCCESS = "CONTACT_CREATED_SUCCESS";
export const CONTACT_DELETED_SUCCESS = "CONTACT_DELETED_SUCCESS";
export const UPDATE_FIELD_SUCCESS = "UPDATE_FIELD_SUCCESS";
export const LOADING = "LOADING";
